# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f28701a320408cd64f215955f4d0f7b67a1366abf32e754d6099fdacd4777542950ae66a360d309935c6fd90dc47ab5268bb487a61ec02344eb1b6d8d4387c5

test:
  secret_key_base: 4975f23f174ccb97150bd7e876d7625ab5784fcf2fecc8a876b7398f387e5cdf084c5da736909eb6f9f753fd06137674e80570a68523d10572cbf8f757e5f530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
